#!/usr/bin/env python3
"""Extract frame polylines and Bezier fits from babyharp_frame.svg.

Reads the hand-drawn paths from ../babyharp_frame.svg, parses each polyline,
fits Schneider Beziers to the three large curves, and writes the result to
../frame_data.py as plain Python literals. babyharp.py imports the result
so it has no runtime dependency on bezierfit.py or the source SVG.

Run from anywhere:
    python3 tools/extract_frame_data.py
"""
from __future__ import annotations
import re, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import numpy as np
from bezierfit import fit_curve

FRAME_SVG = REPO / "babyharp_frame.svg"
OUT_PY    = REPO / "frame_data.py"


def parse_abs_pts(d: str) -> list[tuple[float, float]]:
    out: list[tuple[float, float]] = []
    tokens = re.findall(r'[MmLlHhVvCcSsQqTtAaZz]|-?\d*\.?\d+(?:[eE][+-]?\d+)?', d)
    i = 0; x = y = 0.0; last_cmd = ''; abs_cmd = ''
    while i < len(tokens):
        t = tokens[i]
        if t in 'MmLlHhVvCcSsQqTtAaZz':
            last_cmd = t; abs_cmd = t.upper(); i += 1; continue
        n = float(t)
        if abs_cmd in ('M', 'L'):
            x2 = n if last_cmd.isupper() else x + n
            y2 = float(tokens[i+1]) if last_cmd.isupper() else y + float(tokens[i+1])
            x, y = x2, y2; out.append((x, y)); i += 2
            if last_cmd == 'M': last_cmd = 'L'
            elif last_cmd == 'm': last_cmd = 'l'
        elif abs_cmd == 'H':
            x = n if last_cmd.isupper() else x + n; out.append((x, y)); i += 1
        elif abs_cmd == 'V':
            y = n if last_cmd.isupper() else y + n; out.append((x, y)); i += 1
        elif abs_cmd in ('C', 'S', 'Q', 'T'):
            cnt = {'C': 6, 'S': 4, 'Q': 4, 'T': 2}[abs_cmd]
            xs = [float(tokens[i + k]) for k in range(cnt)]
            i += cnt
            ex = xs[-2] if last_cmd.isupper() else x + xs[-2]
            ey = xs[-1] if last_cmd.isupper() else y + xs[-1]
            x, y = ex, ey; out.append((x, y))
        elif abs_cmd == 'A':
            xs = [float(tokens[i + k]) for k in range(7)]
            i += 7
            ex = xs[-2] if last_cmd.isupper() else x + xs[-2]
            ey = xs[-1] if last_cmd.isupper() else y + xs[-1]
            x, y = ex, ey; out.append((x, y))
        else:
            i += 1
    return out


def schneider(pts, max_error=300.0):
    arr = np.array([list(p) for p in pts], dtype=float)
    bezs = fit_curve(arr, max_error=max_error)
    out = []
    for bz in bezs:
        c1 = (float(bz[1][0]), float(bz[1][1]))
        c2 = (float(bz[2][0]), float(bz[2][1]))
        p3 = (float(bz[3][0]), float(bz[3][1]))
        out.append((c1, c2, p3))
    seq = [(float(bezs[0][0][0]), float(bezs[0][0][1]))] + [b[2] for b in out]
    return seq, out


def main():
    src = FRAME_SVG.read_text()
    def frame_d(pid):
        m = re.search(r'd="([^"]+)"\s+style="[^"]*"\s+id="' + pid + '"', src)
        if not m:
            raise SystemExit(f'path {pid} not found in {FRAME_SVG}')
        return m.group(1)

    d20 = frame_d('path20')
    d68 = frame_d('path68')
    d70 = frame_d('path70')
    d66 = frame_d('path66')
    d72 = frame_d('path72')
    d74 = frame_d('path74')
    d76 = frame_d('path76')

    p20_pts = parse_abs_pts(d20)
    p68_pts = parse_abs_pts(d68)
    p70_pts = parse_abs_pts(d70)
    p20_seq, p20_bez = schneider(p20_pts, 400.0)
    p68_seq, p68_bez = schneider(p68_pts, 300.0)
    p70_seq, p70_bez = schneider(p70_pts, 300.0)
    print(f'p20: {len(p20_pts)} pts -> {len(p20_bez)} bez')
    print(f'p68: {len(p68_pts)} pts -> {len(p68_bez)} bez')
    print(f'p70: {len(p70_pts)} pts -> {len(p70_bez)} bez')

    def emit_pts(name, pts):
        lines = [f'{name} = [']
        for x, y in pts: lines.append(f'    ({x!r}, {y!r}),')
        lines.append(']'); lines.append('')
        return lines
    def emit_bez(name, bez):
        lines = [f'{name} = [']
        for c1, c2, p3 in bez:
            lines.append(f'    (({c1[0]!r}, {c1[1]!r}), ({c2[0]!r}, {c2[1]!r}), ({p3[0]!r}, {p3[1]!r})),')
        lines.append(']'); lines.append('')
        return lines

    out = [
        '"""Frame data for the babyharp12 instrument.',
        '',
        'Auto-generated by tools/extract_frame_data.py from babyharp_frame.svg.',
        'Re-generate this file after editing the frame SVG. babyharp.py imports',
        'from this module, so the main script has no runtime dependency on',
        'bezierfit.py or the source SVG.',
        '"""',
        '',
    ]
    out += emit_pts('P20_PTS', p20_pts)
    out += emit_pts('P68_PTS', p68_pts)
    out += emit_pts('P70_PTS', p70_pts)
    out += emit_pts('P20_SEQ', p20_seq)
    out += emit_bez('P20_BEZ', p20_bez)
    out += emit_pts('P68_SEQ', p68_seq)
    out += emit_bez('P68_BEZ', p68_bez)
    out += emit_pts('P70_SEQ', p70_seq)
    out += emit_bez('P70_BEZ', p70_bez)
    out += [
        f'PATH66_D = {d66!r}',
        f'PATH72_D = {d72!r}',
        f'PATH74_D = {d74!r}',
        f'PATH76_D = {d76!r}',
        '',
    ]
    OUT_PY.write_text('\n'.join(out))
    print(f'wrote {OUT_PY}: {OUT_PY.stat().st_size} bytes')


if __name__ == '__main__':
    main()
